### ISSUE TITLE
ValueError: buffer is smaller than requested size

### ISSUE THREAD

**Issue by biyuehuang** [opencv/open_model_zoo#1001]
Hi, I download & convert deeplabv3 model in python virtual environment. Then vim a json file, 
```
{
    "model": {
        "model_name": "deeplabv3",
        "model": "/home/user/demo/public/deeplabv3/FP32/deeplabv3.xml",
        "weights": "/home/user/demo/public/deeplabv3/FP32/deeplabv3.xml"
    },
    "engine": {
        "config": "/opt/intel/openvino/deployment_tools/open_model_zoo/tools/accuracy_checker/configs/deeplabv3.yml"
    },
    "compression": {
        "target_device": "CPU",
        "algorithms": [
            {
                "name": "DefaultQuantization",
                "preset": "performance",
                "params": {
                    "stat_subset_size": 300
                }
            }
        ]
    }
}
```
And then I modify the VOC2012 datasets' path in dataset_definitation.yml.
 Last I run the command: 
`$pot -c /opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/configs/examples/deeplabv3.json -e`

Error exit:
Traceback (most recent call last):
  File "/home/user/Documents/post/bin/pot", line 11, in <module>
    load_entry_point('pot==1.0', 'console_scripts', 'pot')()
  File "/home/user/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/app/run.py", line 34, in main
    app(sys.argv[1:])
  File "/home/user/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/app/run.py", line 48, in app
    metrics = optimize(config, args.save_model)
  File "/home/user/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/app/run.py", line 99, in optimize
    model = load_model(config.model)
  File "/home/user/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/compression/graph/model_utils.py", line 41, in load_model
    graph_from_ir, meta_data = stdout_redirect(restore_graph_from_ir, xml_path, bin_path)
  File "/home/user/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/compression/utils/logger.py", line 114, in stdout_redirect
    res = fn(*args, **kwargs)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/model_optimizer/mo/utils/ir_reader/restore_graph.py", line 43, in restore_graph_from_ir
    ir = IREngine(path_to_xml, path_to_bin)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/model_optimizer/mo/utils/ir_engine/ir_engine.py", line 51, in __init__
    self.__load_ir()
  File "/opt/intel/openvino_2020.1.023/deployment_tools/model_optimizer/mo/utils/ir_engine/ir_engine.py", line 169, in __load_ir
    self.__load_bin()
  File "/opt/intel/openvino_2020.1.023/deployment_tools/model_optimizer/mo/utils/ir_engine/ir_engine.py", line 142, in __load_bin
    value = np.frombuffer(buffer=bin_buff, dtype=precision, count=size, offset=offset)
ValueError: buffer is smaller than requested size

**Comment by eaidova** [comment]
@biyuehuang  Hi again : )
I see the typo in your POT config (you specify the path to xml twice, instead of bin)
please change:
`"weights": "/home/user/demo/public/deeplabv3/FP32/deeplabv3.xml"` -> `"weights": "/home/user/demo/public/deeplabv3/FP32/deeplabv3.bin"`

**Comment by biyuehuang** [comment]
@eaidova Sorry, I make such a simple mistake. It can work now.
