### ISSUE TITLE
yolov3-tf.yml   TypeError: "None" is expected to be a path-like

### ISSUE THREAD

**Issue by biyuehuang** [opencv/open_model_zoo#1103]
Hi, I create yolov3-tf.json, use yolov3-tf.yml and modify dataset_defines.yml as following
```
""""""
  - name: ms_coco_detection_80_class_without_backgound
    data_source: /home/datasets/coco_2017/val2017/
    annotation_conversion:
      converter: mscoco_detection
      annotation_file: /home/datasets/coco_2017/annotations/instances_val2017.json
      has_background: False
      sort_annotations: True
      use_full_label_map: False
    annotation:  /home/datasets/model_mo/Yolo_v3/mscoco_det_80.pickle
    dataset_meta:  /home/datasets/model_mo/Yolo_v3/mscoco_det_80.json
"""""""
```
then I run $ pot -c /opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit/configs/examples/yolo-v3-tf.json -e
"""""
```
Output log dir: ./results/yolo-v3-tf_DefaultQuantization/2020-05-14_10-25-21
Creating pipeline:
Algorithm: DefaultQuantization
Parameters:
        stat_subset_size           : 300
        target_device              : CPU
===========================================================================
Traceback (most recent call last):
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/utils.py", line 47, in get_path
    path = Path(entry)
  File "/usr/lib/python3.6/pathlib.py", line 1001, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.6/pathlib.py", line 656, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.6/pathlib.py", line 640, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/intel/Documents/post/bin/pot", line 11, in <module>
    load_entry_point('pot==1.0', 'console_scripts', 'pot')()
  File "/home/intel/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/app/run.py", line 34, in main
    app(sys.argv[1:])
  File "/home/intel/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/app/run.py", line 48, in app
    metrics = optimize(config, args.save_model)
  File "/home/intel/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/app/run.py", line 96, in optimize
    engine = ACEngine(config.engine)
  File "/home/intel/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/compression/engines/ac_engine.py", line 44, in __init__
    stdout_redirect(self._model_evaluator.select_dataset, self._evaluation_dataset_tag)
  File "/home/intel/Documents/post/lib/python3.6/site-packages/pot-1.0-py3.6.egg/compression/utils/logger.py", line 114, in stdout_redirect
    res = fn(*args, **kwargs)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py", line 182, in select_dataset
    dataset_attributes = create_dataset_attributes(self.dataset_config, dataset_tag)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/quantization_model_evaluator.py", line 409, in create_dataset_attributes
    data_reader = BaseReader.provide(data_reader_type, data_source, data_reader_config)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/dependency.py", line 67, in provide
    return root_provider(*args, **kwargs)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py", line 92, in __init__
    self.configure()
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py", line 112, in configure
    self.data_source = get_path(self.data_source, is_directory=True)
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/utils.py", line 49, in get_path
    raise TypeError('"{}" is expected to be a path-like'.format(entry))
TypeError: "None" is expected to be a path-like
```
"""""""
attatch my  yolov3-tf.json
```
{
    "model": {
        "model_name": "yolov3",
        "model": "/home/datasets/model_mo/Yolo_v3/yolov3_FP32.xml",
        "weights": "/home/datasets/model_mo/Yolo_v3/yolov3_FP32.bin"
    },
    "engine": {
        "config": "/opt/intel/openvino/deployment_tools/open_model_zoo/tools/accuracy_checker/configs/yolo-v3-tf.yml"
    },
    "compression": {
        "target_device": "CPU",
        "algorithms": [
            {
                "name": "DefaultQuantization",
                "preset": "performance",
                "params": {
                    "stat_subset_size": 300
                }
            }
        ]
    }
}
```

**Comment by eaidova** [comment]
Hi @biyuehuang, please make sure that `global_definitions` section present in your yolo-v3-tf.yml, like here:
https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/configs/yolo-v3-tf.yml#L122

**Comment by biyuehuang** [comment]
> Hi @biyuehuang, please make sure that `global_definitions` section presents in your yolo-v3-tf.yml, like here:
> https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/configs/yolo-v3-tf.yml#L122

Yes,  "global_definitions: ../dataset_definitions.yml" still in  yolo-v3-tf.yml.  I have not modified yolo-v3-tf.yml

**Comment by eaidova** [comment]
@biyuehuang  okey, then please make sure that file which you modify to set dataset path located on this place

**Comment by biyuehuang** [comment]
> @biyuehuang okey, then please make sure that file which you modify to set dataset path located on this place

Yes, I modify dataset_definitions.yml as following

""""""
  - name: ms_coco_detection_80_class_without_backgound
    data_source: /home/datasets/coco_2017/val2017/
    annotation_conversion:
      converter: mscoco_detection
      annotation_file: /home/datasets/coco_2017/annotations/instances_val2017.json
      has_background: False
      sort_annotations: True
      use_full_label_map: False
    annotation:  /home/datasets/model_mo/Yolo_v3/mscoco_det_80.pickle
    dataset_meta:  /home/datasets/model_mo/Yolo_v3/mscoco_det_80.json
"""""""

**Comment by biyuehuang** [comment]
Hi, @eaidova eaidova, We solve this error now. Because Openvino 2020.01 dataset_definitions.yml make mistake:
"name: ms_coco_detection_80_class_without_backgound" should be "name: ms_coco_detection_80_class_without_backg**r**ound", misspell background.
