### ISSUE TITLE
How to add annotation metadata?

### ISSUE THREAD

**Issue by tlsdmstn56-2** [opencv/open_model_zoo#1292]
https://github.com/opencv/open_model_zoo/blob/912eeaddc034e31dedd34617d82bcc2ddf83e542/tools/accuracy_checker/accuracy_checker/representation/regression_representation.py#L59-L71

```
Traceback (most recent call last):
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/main.py", line 259, in main
    evaluator.process_dataset(args.stored_predictions, progress_reporter=progress_reporter)
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/evaluators/model_evaluator.py", line 215, in process_dataset_sync
    self.metric_executor.update_metrics_on_batch(batch_input_ids, annotations, predictions)
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/metrics/metric_executor.py", line 97, in update_metrics_on_batch
    results[input_id] = self.update_metrics_on_object(single_annotation, single_prediction)
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/metrics/metric_executor.py", line 81, in update_metrics_on_object
    metric_results.append(metric.metric_fn.submit(annotation, prediction))
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/metrics/metric.py", line 189, in submit
    metric_result = self.update(annotation_, prediction_)
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/metrics/regression.py", line 318, in update
    avg_result /= np.maximum(annotation.interocular_distance, np.finfo(np.float64).eps)
  File "/home/user/venv/lib/python3.6/site-packages/accuracy_checker-0.7.6-py3.6.egg/accuracy_checker/representation/regression_representation.py", line 63, in interocular_distance
    np.mean(self.x_values[self.metadata['left_eye']]),
KeyError: 'left_eye'
```

Hello, 

I am trying to use FacialLandmarksAnnotation and FacialLandmarksPrediction to use normed_error metric, but metadata does not have `left_eye` so there raise `KeyError`. I tried to add metadata as following, but there was no use.

```python
class SomeConverter(BaseFormatConverter):
    __provider__ = 'example'
    annotation_types = (FacialLandmarksAnnotation, )

    # some codes.. configure, parameters ...

    def convert(self, check_content=False, progress_callback=None, progress_interval=100, **kwargs):
        FacialLandmarksAnnotation.metadata = {'left_eye':0, 'right_eye':0}
        # other codes
```

How can I add annotation metadata? If there is documentations for this, where can I find them?

Thank you

**Comment by eaidova** [comment]
left_eye and right_eye are coordinates of points which represents eyes landmarks in your dataset respectively, they used for calculation interocular distance for metric result normalization.
How to set it, you can find for example in VGG Face dataset converter

https://github.com/opencv/open_model_zoo/blob/master/tools/accuracy_checker/accuracy_checker/annotation_converters/vgg_face_regression.py#L65-L67

```python
            annotation = FacialLandmarksAnnotation(identifier, x_values, y_values)
            annotation.metadata['left_eye'] = 0
            annotation.metadata['right_eye'] = 1
```
You last solution was incorrect because you try to add metadata to class, but you need to provide it to its specific instance

**Comment by tlsdmstn56-2** [comment]
Now it works, thank you 👍
