### ISSUE TITLE
object detection demo float not iterable

### ISSUE THREAD

**Issue by accateo** [opencv/open_model_zoo#253]
Hi,
when I try to run the script object_detection_demo_yolov3_async.py  with a USB camera like input, I have this error:

```
Traceback (most recent call last):
  File "object_detection_demo_ssd_async.py", line 186, in <module>
    sys.exit(main() or 0)
  File "object_detection_demo_ssd_async.py", line 138, in main
    for obj in res[0][0]:
TypeError: 'numpy.float32' object is not iterable
```

At line 138 I have:

```
# Parse detection results of the current request
            res = exec_net.requests[cur_request_id].outputs[out_blob]
            for obj in res[0][0]:
                # Draw only objects when probability more than specified threshold
                if obj[2] > args.prob_threshold:
                    xmin = int(ob....
```
Any idea?
Thanks

**Comment by dkurt** [comment]
Hi!

Please provide more details: specify model, output of `print(res)` command before it's used. Thanks!

**Comment by accateo** [comment]
This is the output of print(res)

```
[ INFO ] [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
```

Commands before are the same in the example:

```
# Main sync point:
        # in the truly Async mode we start the NEXT infer request, while waiting for the CURRENT to complete
        # in the regular mode we start the CURRENT request and immediately wait for it's completion
        inf_start = time.time()
        if is_async_mode:
            in_frame = cv2.resize(next_frame, (w, h))
            in_frame = in_frame.transpose((2, 0, 1))  # Change data layout from HWC to CHW
            in_frame = in_frame.reshape((n, c, h, w))
            exec_net.start_async(request_id=next_request_id, inputs={input_blob: in_frame})
        else:
            in_frame = cv2.resize(frame, (w, h))
            in_frame = in_frame.transpose((2, 0, 1))  # Change data layout from HWC to CHW
            in_frame = in_frame.reshape((n, c, h, w))
            exec_net.start_async(request_id=cur_request_id, inputs={input_blob: in_frame})
        if exec_net.requests[cur_request_id].wait(-1) == 0:
            inf_end = time.time()
            det_time = inf_end - inf_start
```

Models are a normal xml and bin file...

The example file is here:
https://github.com/opencv/open_model_zoo/blob/master/demos/python_demos/object_detection_demo_ssd_async/object_detection_demo_ssd_async.py

**Comment by dkurt** [comment]
@accateo, Thanks! Let me clarify, you use YOLO or SSD? Which version of YOLO if so?

**Comment by accateo** [comment]
SSD version

**Comment by IRDonch** [comment]
> Models are a normal xml and bin file...

Which model, specifically? The value of `res` that you posted doesn't look like it came out of a supported network. This demo only supports networks with outputs of dimensions 1x1x200x7. Some examples of those are listed in `models.lst` in the demo directory.
