### ISSUE TITLE
#dldt i was trying to convert tensorflow  fastercnn frozengraph.pb which i trained with custom data to modeloptimizer ir file i am getting this error

### ISSUE THREAD

**Issue by manoj652** [opencv/open_model_zoo#7]
#dldt The Preprocessor block has been removed. Only nodes performing mean value subtraction and scaling (if applicable) are kept.
[ ERROR ] Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work.

**Comment by lazarevevgeny** [comment]
@manoj652 Looks like the sub-graph replacement configuration file that you specified with the `--tensorflow_object_detection_api_pipeline_config` command line parameter is not suitable for your version of the FasterRCNN topology. Could you re-run the Model Optimizer with the `--log_level DEBUG` command line option and attach the log file?

**Comment by manoj652** [comment]
#dldt @lazarevevgeny 


--log_level DEBUG
SecondStagePostprocessor/BatchMultiClassNonMaxSuppression/map/while/MultiClassNonMaxSuppression/ChangeCoordinateFrame/truediv_1/mul_
SecondStagePostprocessor/scale_logits/reciprocal_
SecondStagePostprocessor/scale_logits/mul_
[ ERROR ] Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work.
[ 2018-11-15 21:55:55,244 ] [ DEBUG ] [ main:327 ] Traceback (most recent call last):
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/main.py", line 321, in main
return driver(argv)
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/main.py", line 263, in driver
mean_scale_values=mean_scale)
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/pipeline/tf.py", line 171, in tf2nx
class_registration.apply_replacements(graph, class_registration.ClassType.FRONT_REPLACER)
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/utils/class_registration.py", line 102, in apply_replacements
replacer.find_and_replace_pattern(graph)
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/front/tf/replacement.py", line 91, in find_and_replace_pattern
self.replace_sub_graph(graph, match)
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/mo/front/common/replacement.py", line 115, in replace_sub_graph
new_sub_graph = self.generate_sub_graph(graph, match)
File "/home/manojvasi/intel/computer_vision_sdk_2018.3.343/deployment_tools/model_optimizer/extensions/front/tf/ObjectDetectionAPI.py", line 261, in generate_sub_graph
format(proposal_nodes_ids))
mo.utils.error.Error: Found the following nodes '[]' with name 'swapped_proposals' but there should be exactly 1. Looks like ObjectDetectionAPIProposalAndROIPoolingReplacement replacement didn't work.

**Comment by snosov1** [comment]
Is this still relevant or we can close?

**Comment by snosov1** [comment]
Please, reopen, if necessary.
