### ISSUE TITLE
Post-Training Optimization with accuracy_checker/configs/deeplabv3.yml

### ISSUE THREAD

**Issue by biyuehuang** [opencv/open_model_zoo#990]
Hi, I follow this website https://docs.openvinotoolkit.org/latest/_README.html for quantization. I use my FP32 & FP16.xml/bin path in accuracy_checker/configs/deeplabv3.yml. Then use command$pot -c ../../open_model_zoo\tools\accuracy_checker\configs\deeplabv3.yml
Error:
 File "C:\Program Files (x86)\IntelSWTools\openvino\deployment_tools\tools\post_training_optimization_toolkit\compression\configs\config.py", line 77, in _validate_model_conf
    raise RuntimeError('Path to input model xml is required.')
RuntimeError: Path to input model xml is required.

**Comment by eaidova** [comment]
Hi @biyuehuang,
Please pay attention that Posttraining optimization tool required own config file format. It is different from accuracy checker config and moreover may include the path to accuracy checker config for engine section,
please take a look https://docs.openvinotoolkit.org/latest/_configs_README.html

cc @kchechil @AlexKoff88

**Comment by biyuehuang** [comment]
Hi @eaidova eaidova,
I follow your website, download deeplabv3.tar.gz, and convert it to FP32 & FP16 xml/bin. Now I use $sudo pot -c ./libs/open_model_zoo/tools/accuracy_checker/configs/deeplabv3.yml
Error exit:
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/graph/model_utils.py", line 17, in <module>
    import mo
ModuleNotFoundError: No module named 'mo'
But I have source envirorment, and script "$python3  >>import mo" is ok. Are there anything wrong about new module pot-1.0-py3.6.egg and Openvino?


> Hi @biyuehuang,
> Please pay attention that Posttraining optimization tool required own config file format. It is different from accuracy checker config and moreover may include the path to accuracy checker config for engine section,
> please take a look https://docs.openvinotoolkit.org/latest/_configs_README.html
> 
> cc @kchechil @AlexKoff88

**Comment by eaidova** [comment]
@biyuehuang , I have a question, do you install the POT with sudo or without it? Could you please try to run without sudo?
(I see that the console script which works correctly was called without sudo)

**Comment by biyuehuang** [comment]
@eaidova  No, I can't. Because I use install setup.py without sudo, POT can't install sucessful.
/opt/intel/openvino/deployment_tools/tools/post_training_optimization_toolkit$ python3 setup.py install
running install
running bdist_egg
running egg_info
error: [Errno 13] Permission denied

**Comment by eaidova** [comment]
@biyuehuang, could you please check
```
sudo python3 -c "import mo"
```
Does it work in your environment?

**Comment by biyuehuang** [comment]
@eaidova , $sudo python3 -c "import mo"  doesn't work. But $python3 -c "import mo" work.
When I use $pot -c ./libs/open_model_zoo/tools/accuracy_checker/configs/deeplabv3.yml

Error Exit:
/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/algorithms/quantization/optimization/algorithm.py:39: UserWarning: Nevergrad package could not be imported. Consider installing itusing pip. Note that nevergrad is compatible only with Python 3.6+
  warnings.warn('Nevergrad package could not be imported. Consider installing it'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/utils/ac_imports.py", line 18, in <module>
    from libs.open_model_zoo.tools.accuracy_checker.\
ModuleNotFoundError: No module named 'libs.open_model_zoo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/pot", line 11, in <module>
    load_entry_point('pot==1.0', 'console_scripts', 'pot')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/app/run.py", line 20, in <module>
    from compression.configs.config import Config
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/configs/config.py", line 22, in <module>
    from ..utils.ac_imports import ConfigReader
  File "/usr/local/lib/python3.6/dist-packages/pot-1.0-py3.6.egg/compression/utils/ac_imports.py", line 25, in <module>
    from accuracy_checker.evaluators.quantization_model_evaluator import ModelEvaluator
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/__init__.py", line 17, in <module>
    from .model_evaluator import ModelEvaluator
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/evaluators/model_evaluator.py", line 22, in <module>
    from ..dataset import Dataset
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/dataset.py", line 21, in <module>
    from .annotation_converters import BaseFormatConverter, save_annotation, make_subset, analyze_dataset
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/__init__.py", line 18, in <module>
    from .convert import make_subset, save_annotation, analyze_dataset
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/annotation_converters/convert.py", line 27, in <module>
    from ..representation import ReIdentificationClassificationAnnotation
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/__init__.py", line 36, in <module>
    from .segmentation_representation import (
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/representation/segmentation_representation.py", line 27, in <module>
    from ..data_readers import BaseReader
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/__init__.py", line 17, in <module>
    from .data_reader import (
  File "/opt/intel/openvino_2020.1.023/deployment_tools/open_model_zoo/tools/accuracy_checker/accuracy_checker/data_readers/data_reader.py", line 26, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/graph_pb2.py", line 16, in <module>
    from tensorflow.core.framework import node_def_pb2 as tensorflow_dot_core_dot_framework_dot_node__def__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/node_def_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/core/framework/resource_handle_pb2.py", line 23, in <module>
    serialized_pb=_b('\n/tensorflow/core/framework/resource_handle.proto\x12\ntensorflow\"r\n\x13ResourceHandleProto\x12\x0e\n\x06\x64\x65vice\x18\x01 \x01(\t\x12\x11\n\tcontainer\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x11\n\thash_code\x18\x04 \x01(\x04\x12\x17\n\x0fmaybe_type_name\x18\x05 \x01(\tBn\n\x18org.tensorflow.frameworkB\x0eResourceHandleP\x01Z=github.com/tensorflow/tensorflow/tensorflow/go/core/framework\xf8\x01\x01\x62\x06proto3')
TypeError: __new__() got an unexpected keyword argument 'serialized_options'

**Comment by eaidova** [comment]
@biyuehuang, which tensorflow version installed in your environment?
I think, it makes sence to start with clear environment to avoid sudo usage.
You can create virtual environment using this instruction:
In order to use virtual environment you should install it first:
```bash
python3 -m pip install virtualenv
python3 -m virtualenv -p `which python3` <directory_for_environment>
```
Before starting to work inside virtual environment, it should be activated:
```
source <directory_for_environment>/bin/activate
```
Virtual environment can be deactivated using command
```
deactivate
```
Then when virtual environment activated, please install model_optimizer dependecies
```
pip -r <openvino>/deployment_tools/model_optimizer/requirements.txt
pip -r <openvino>/deployment_tools/model_optimizer/requirements_caffe.txt
pip -r <openvino>/deployment_tools/model_optimizer/requirements_tf.txt
pip -r /<openvino>/deployment_tools/model_optimizer/requirements_mxnet.txt
pip -r <openvino>/deployment_tools/model_optimizer/requirements_onnx.txt
```
Install AccuracyChecker
```
cd <openvino>/deployment_tools/open_model_zoo/tools/accuracy_checker
python setup.py install
```
Install Posttraining Optimization Toolkit:
```
cd <openvino>/deployment_tools/tools/post_training_optimization_toolkit
python setup.py install
``` 

After that you will be able to run pot without sudo.

But there is another note on which I want pay your attention.

**AccuracyChecker config and POT config are different things**.
The accuracy_checker config is yaml file which describe how to measure the accuracy of model (currently you try to use this config in -c argument), while the POT config is json, which describes where model can be found, how it should be evaluated and which compression algorithm should be used. For this model we provide only AC config, so you need to write POT config by yourself.
you can find how to write it in this [doc](https://docs.openvinotoolkit.org/latest/_configs_README.html) and find config examples and templates in <openvino>/deployment_tools/tools/post_training_optimization_toolkit/configs.
Also you can find instruction how examples should be used [here](https://docs.openvinotoolkit.org/latest/_configs_examples_README.html)

**Comment by biyuehuang** [comment]
@eaidova Thank you very much. I make a mistake at first. The command should be $pot -c /path/to/POT/config/*.json
